# Generated by Django 5.1.4 on 2025-01-03 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_userprofile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='requested_author',
            field=models.BooleanField(default=False),
        ),
    ]
